
import { useState, useCallback } from "react";
import { useStaff } from "@/hooks/use-staff";
import { useEvents } from "@/hooks/events/use-events";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";
import { toast } from "@/hooks/use-toast";
import { Event, EventType } from "@/types/models";
import { MultiStaffSelector } from "./multi-staff-selector";
import { Calendar, Clock, MapPin, User, Tag, AlertCircle } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

interface AddEventDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onEventAdded: () => void;
}

export default function AddEventDialog({ open, onOpenChange, onEventAdded }: AddEventDialogProps) {
  const { staff, loading: staffLoading } = useStaff();
  const { addEvent } = useEvents();

  // Form state
  const [name, setName] = useState("");
  const [date, setDate] = useState("");
  const [startTime, setStartTime] = useState("");
  const [endTime, setEndTime] = useState("");
  const [location, setLocation] = useState("");
  const [organizer, setOrganizer] = useState("");
  const [type, setType] = useState<EventType>("Documentation");
  const [videographerIds, setVideographerIds] = useState<string[]>([]);
  const [photographerIds, setPhotographerIds] = useState<string[]>([]);
  const [ignoreScheduleConflicts, setIgnoreScheduleConflicts] = useState(false);
  const [ccsOnlyEvent, setCcsOnlyEvent] = useState(false);
  const [sendEmailNotifications, setSendEmailNotifications] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const resetForm = useCallback(() => {
    setName("");
    setDate("");
    setStartTime("");
    setEndTime("");
    setLocation("");
    setOrganizer("");
    setType("Documentation");
    setVideographerIds([]);
    setPhotographerIds([]);
    setIgnoreScheduleConflicts(false);
    setCcsOnlyEvent(false);
    setSendEmailNotifications(true);
    setIsSubmitting(false);
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isSubmitting) return;

    try {
      setIsSubmitting(true);

      if (!name || !date || !startTime || !endTime || !location) {
        toast({
          title: "Missing Fields",
          description: "Please fill in all required fields.",
          variant: "destructive",
        });
        return;
      }

      const eventData: Omit<Event, "id" | "videographers" | "photographers"> = {
        name,
        logId: "", // Will be generated by the hook
        date,
        startTime,
        endTime,
        location,
        organizer: organizer || null,
        type,
        status: "Upcoming",
        ignoreScheduleConflicts,
        ccsOnlyEvent,
        isBigEvent: false,
        bigEventId: null
      };

      await addEvent(
        eventData,
        videographerIds,
        photographerIds,
        sendEmailNotifications
      );

      resetForm();
      onOpenChange(false);
      onEventAdded();
    } catch (error) {
      console.error("Error adding event:", error);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleOpenChange = (newOpen: boolean) => {
    if (!newOpen && !isSubmitting) {
      resetForm();
    }
    onOpenChange(newOpen);
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto animate-fade-in">
        <DialogHeader className="animate-slide-in-right">
          <DialogTitle className="flex items-center gap-2 text-xl font-semibold">
            <Calendar className="h-5 w-5 text-primary" />
            Add New Event
          </DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-6 animate-fade-in-up">
          {/* Basic Information */}
          <Card className="animate-fade-in-up">
            <CardContent className="p-6 space-y-4">
              <div className="flex items-center gap-2 mb-4">
                <Tag className="h-4 w-4 text-primary" />
                <h3 className="font-medium">Basic Information</h3>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Event Name *</Label>
                  <Input
                    id="name"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="Enter event name"
                    required
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="type">Event Type *</Label>
                  <Select value={type} onValueChange={(value) => setType(value as EventType)}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Documentation">Documentation</SelectItem>
                      <SelectItem value="Live Streaming">Live Streaming</SelectItem>
                      <SelectItem value="Photo & Video">Photo & Video</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="organizer">Organizer</Label>
                <div className="relative">
                  <User className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                  <Input
                    id="organizer"
                    value={organizer}
                    onChange={(e) => setOrganizer(e.target.value)}
                    placeholder="Enter organizer name"
                    className="pl-10"
                  />
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Date & Time */}
          <Card className="animate-fade-in-up">
            <CardContent className="p-6 space-y-4">
              <div className="flex items-center gap-2 mb-4">
                <Clock className="h-4 w-4 text-primary" />
                <h3 className="font-medium">Date & Time</h3>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="date">Date *</Label>
                  <Input
                    id="date"
                    type="date"
                    value={date}
                    onChange={(e) => setDate(e.target.value)}
                    required
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="startTime">Start Time *</Label>
                  <Input
                    id="startTime"
                    type="time"
                    value={startTime}
                    onChange={(e) => setStartTime(e.target.value)}
                    required
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="endTime">End Time *</Label>
                  <Input
                    id="endTime"
                    type="time"
                    value={endTime}
                    onChange={(e) => setEndTime(e.target.value)}
                    required
                  />
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Location */}
          <Card className="animate-fade-in-up">
            <CardContent className="p-6 space-y-4">
              <div className="flex items-center gap-2 mb-4">
                <MapPin className="h-4 w-4 text-primary" />
                <h3 className="font-medium">Location</h3>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="location">Location *</Label>
                <Textarea
                  id="location"
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                  placeholder="Enter event location"
                  required
                  rows={2}
                />
              </div>
            </CardContent>
          </Card>

          {/* Staff Assignment */}
          <Card className="animate-fade-in-up">
            <CardContent className="p-6 space-y-4">
              <div className="flex items-center gap-2 mb-4">
                <User className="h-4 w-4 text-primary" />
                <h3 className="font-medium">Staff Assignment</h3>
              </div>
              
              <div className="space-y-4">
                <MultiStaffSelector
                  staff={staff}
                  eventDate={date}
                  startTime={startTime}
                  endTime={endTime}
                  selectedVideographerIds={videographerIds}
                  selectedPhotographerIds={photographerIds}
                  onVideographerChange={setVideographerIds}
                  onPhotographerChange={setPhotographerIds}
                  ignoreScheduleConflicts={ignoreScheduleConflicts}
                  ccsOnlyEvent={ccsOnlyEvent}
                  loading={staffLoading}
                />
              </div>
            </CardContent>
          </Card>

          {/* Options */}
          <Card className="animate-fade-in-up">
            <CardContent className="p-6 space-y-4">
              <div className="flex items-center gap-2 mb-4">
                <AlertCircle className="h-4 w-4 text-primary" />
                <h3 className="font-medium">Options</h3>
              </div>
              
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label>Ignore Schedule Conflicts</Label>
                    <p className="text-sm text-muted-foreground">
                      Allow assignment even if staff has scheduling conflicts
                    </p>
                  </div>
                  <Switch
                    checked={ignoreScheduleConflicts}
                    onCheckedChange={setIgnoreScheduleConflicts}
                  />
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label>CCS Only Event</Label>
                    <p className="text-sm text-muted-foreground">
                      Show only CCS staff members for assignment
                    </p>
                  </div>
                  <Switch
                    checked={ccsOnlyEvent}
                    onCheckedChange={setCcsOnlyEvent}
                  />
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label>Send Email Notifications</Label>
                    <p className="text-sm text-muted-foreground">
                      Notify assigned staff via email
                    </p>
                  </div>
                  <Switch
                    checked={sendEmailNotifications}
                    onCheckedChange={setSendEmailNotifications}
                  />
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Submit Button */}
          <div className="flex justify-end gap-3 pt-4 animate-fade-in-up">
            <Button
              type="button"
              variant="outline"
              onClick={() => handleOpenChange(false)}
              disabled={isSubmitting}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={isSubmitting}
              className="hover-scale"
            >
              {isSubmitting ? "Creating..." : "Create Event"}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
